version: '3.9'

services:
  app:
    build: .
    container_name: collage_app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  redis:
    image: redis:alpine
    container_name: collage_redis
    restart: always
    ports:
      - '6379:6379'
