version: '3.9'

services:
  app:
    build: .
    container_name: collage_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    restart: on-failure

  redis:
    image: redis:latest
    container_name: collage_redis
    restart: always
    ports:
      - "6379:6379"
